schema_version = 1
bin_dir = "/home/vscode/bin"
debug_mode = false
log_level = "INFO"
blocklist = []
cron_interval = 6
enable_notifications = true

[global_preferences]
launch_method = "auto"
custom_args = []

[global_preferences.env_vars]
